infrastructure:
  env: local
spring:
  application:
    name: notification-service
  cloud:
    config:
      enabled: false
  kafka:
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094
      - localhost:9095
      - localhost:9096
      - localhost:9097
    consumer:
      enable-auto-commit: false
      isolation-level: read_committed
      group-id: ${infrastructure.env}-appointment-notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      max-poll-records: 10
      properties:
        max.poll.interval.ms: 600000
    listener:
      ack-mode: manual_immediate
      concurrency: 1
      auto-startup: true
    properties:
      security.protocol: PLAINTEXT
      sasl.mechanism: PLAIN
  mail:
    host: smtp.gmail.com
    port: 587
    username: ""
    password: ""
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.debug: true
app:
  kafka:
    consumer:
      notification-topic: appointment-system-notifications
  encryption-key: ""
  mail:
    from-address: ${spring.mail.username}

server:
  port: 9002
logging:
  level:
    root: error
    co.appointment.service.KafkaConsumerService: info
